// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDANqRpmdHt2b8gKiBStW8HYtRR0QboXjc',
    appId: '1:224500662678:web:3e124e378672ca84f31db7',
    messagingSenderId: '224500662678',
    projectId: 'flutterpractice-77380',
    authDomain: 'flutterpractice-77380.firebaseapp.com',
    storageBucket: 'flutterpractice-77380.firebasestorage.app',
    measurementId: 'G-9DV8PXZNY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj2GyMysuQmKzxcrwRp4zlqklM1k-5CBw',
    appId: '1:224500662678:android:b92d1c56232bfc0df31db7',
    messagingSenderId: '224500662678',
    projectId: 'flutterpractice-77380',
    storageBucket: 'flutterpractice-77380.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQlPrM9zjT8Nz1fur08a6e99fe8yLuOO4',
    appId: '1:224500662678:ios:c1b51b6d57bd09e0f31db7',
    messagingSenderId: '224500662678',
    projectId: 'flutterpractice-77380',
    storageBucket: 'flutterpractice-77380.firebasestorage.app',
    iosBundleId: 'com.flutterpractices.flutterpractices',
  );
}
